services:
  - type: web
    name: clase-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/salud
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: SEED
        value: "false"
